version: 0.2

phases:
  install:
    commands:
      - npm i npm@latest -g
      - npm i @quasar/cli -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - quasar build
  post_build:
    commands:
      - aws s3 sync $CODEBUILD_SRC_DIR/dist/spa s3://brie.aws.everything.moe
